---
- hosts: all
  become: true
  # gather_facts: false

  tasks:
    - name: Install security updates
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      loop:
        - openssl
        - openssh
      ignore_errors: yes
    - name: Check if docker is installed
      ansible.builtin.command: docker --version
      register: output
      ignore_errors: yes
    - ansible.builtin.debug:
        var: output
    # Update the apt cache before installing -
    # Make sure you update the package list before trying to install anything:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install docker
      ansible.builtin.apt:
        name: docker.io
        state: present
      when: output.failed
